"""Generate the broker capability matrix from the profile registry (#1626).

The answer to "what can each connector actually do" lived in per-connector
code and tribal knowledge. The profiles already declare it: environment,
transport, read-only vs order-capable, and the capability tuple. This renders
them into the published table, and the drift test in
``tests/test_capability_matrix.py`` fails CI the moment the table and the
registry disagree, so the doc cannot go stale.

Regenerate after touching connector profiles:

    python -m src.trading.capability_matrix
"""

from __future__ import annotations

from pathlib import Path

from src.trading.profiles import BUILTIN_PROFILES

DOC_PATH = Path(__file__).resolve().parents[3] / "docs" / "broker-capabilities.md"

_HEADER = """# Broker capability matrix

<!-- GENERATED by `python -m src.trading.capability_matrix`; do not edit by hand. -->

What each built-in connector profile can do, generated from the profile
registry (`agent/src/trading/profiles.py`). An order-capable profile still goes
through the mandate gate: placement on live funds is authorized only with a
mandate in place.

| Connector | Profile | Environment | Transport | Mode | Capabilities |
| --- | --- | --- | --- | --- | --- |
"""


def render() -> str:
    rows = []
    for profile in sorted(BUILTIN_PROFILES, key=lambda p: (p.connector, p.id)):
        caps = ", ".join(f"`{c}`" for c in profile.capabilities)
        mode = "read-only" if profile.readonly else "order-capable"
        rows.append(
            "| {} | {} | {} | {} | {} | {} |".format(
                profile.connector,
                profile.id,
                profile.environment,
                profile.transport,
                mode,
                caps,
            )
        )
    return _HEADER + "\n".join(rows) + "\n"


def main() -> None:
    DOC_PATH.parent.mkdir(parents=True, exist_ok=True)
    DOC_PATH.write_text(render(), encoding="utf-8")
    print(f"wrote {DOC_PATH} ({len(BUILTIN_PROFILES)} profiles)")


if __name__ == "__main__":
    main()
